stages:
    - build

build:
    stage: build
    image: rust:latest
    before_script:
        - rustup component add rust-src
    script:
        - rustc --version && cargo --version
        - make
        - make DEBUG=n
    artifacts:
        expire_in: 1 week
        paths:
            - target/x86_64-xen-pv/debug/oxerun
            - target/x86_64-xen-pv/release/oxerun
